### ISSUE TITLE
Passing samples instead of filepath to get embeddings

### ISSUE THREAD

**Issue by delip** [juanmc2005/SpeakerEmbeddingLossComparison#1]
I already have the audio file loaded and I want to avoid an extra file I/O by using this API:

```
emb1 = model({'audio': '/path/to/file1.wav'})
```

Is there a way to pass the samples and sampling rate to get the embedding?

**Comment by juanmc2005** [comment]
Hello,

For the record, if you have a waveform loaded as a numpy array, I believe pyannote let's you bypass the file loading with the 'waveform' key:

```python
emb1 = model({'waveform': wave})
```

Notice that for this to work, the waveform has to have shape `(seq_len, 1)`.
