### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by juanting** [juanmc2005/SpeakerEmbeddingLossComparison#3]
Thanks for sharing the project. As a newcomer in this field, I want to ask that whether I can use your pre-trained model in genarating embedding instead of load it with torch.hub.load? How should i change it? Looking for your reply.

**Comment by juanmc2005** [comment]
Hello, thank you for your interest in my work!

I'm not sure I understand your question, the model you obtain from torch.hub is the encoder, which means that all it can do is generate speaker embeddings given an audio file. What's interesting then is that you can compare these embeddings directly without training an additional model.

What you need to do to obtain an embedding is:
```python
# load pretrained model from torch.hub
import torch
model = torch.hub.load('pyannote/pyannote-audio', 'emb')

# extract embeddings for the whole file
embedding = model({'audio': '/path/to/file.wav'})
```

Alternatively you can also load the checkpoint in this repo as shown in the [reproduce notebook](https://github.com/juanmc2005/SpeakerEmbeddingLossComparison/blob/master/reproduce.ipynb) under the section "Loading the Pretrained Model".

I hope this answers your question :)

**Comment by juanting** [comment]
> Hello, thank you for your interest in my work!
> 
> I'm not sure I understand your question, the model you obtain from torch.hub is the encoder, which means that all it can do is generate speaker embeddings given an audio file. What's interesting then is that you can compare these embeddings directly without training an additional model.
> 
> What you need to do to obtain an embedding is:
> 
> ```python
> # load pretrained model from torch.hub
> import torch
> model = torch.hub.load('pyannote/pyannote-audio', 'emb')
> 
> # extract embeddings for the whole file
> embedding = model({'audio': '/path/to/file.wav'})
> ```
> 
> Alternatively you can also load the checkpoint in this repo as shown in the [reproduce notebook](https://github.com/juanmc2005/SpeakerEmbeddingLossComparison/blob/master/reproduce.ipynb) under the section "Loading the Pretrained Model".
> 
> I hope this answers your question :)

Thanks for your reply. I have run the example you gave, and I find that embedding shape of a piece of audio is [x, 256]. This means that if I want to get a one-dimensional embedding, does it need to average or other future treatment by myself?  For one audio, I just want to use one embedding to represent. Looking forward to your reply.

**Comment by juanmc2005** [comment]
That's correct, the model will calculate embeddings over sliding windows of the audio file, which is necessary to deal with arbitrarily long sequences. In our experiments we use a simple mean at inference time, but you can aggregate them in any way you wish.

That said, I don't know why your embedding dimension is 256, it should be 512 unless it's been changed in pyannote. In any case, if you want the closest results to this work and your file is considerably longer than 3s, I recommend you use the model hosted in this repo. The main difference is that the model on torch.hub was trained on variable length windows so it's easier to extend to other scenarios, while ours is trained on 3s windows. To do this you'll need to use the [Pretrained](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/features/pretrained.py) class:

```python
from pyannote.audio.features import Pretrained
model = Pretrained(
    'models/AAM/train/VoxCeleb.SpeakerVerification.VoxCeleb2.train/validate_equal_error_rate/'
    'VoxCeleb.SpeakerVerification.VoxCeleb1_X.development', duration=3.0, step=0.0333)

print(f'Embeddings of {model.sliding_window.duration:g}s duration and of dimension {model.dimension:d}, '
      f'extracted every {1000 * model.sliding_window.step:g}ms')
```

Where `duration` is the duration of the sliding window in seconds and `step` is the ratio of the window that's used as step.
This should print `Embeddings of 3s duration and of dimension 512, extracted every 99.9ms`.
